[package]
name = "genetic-algorithm"
version = "0.1.0"
authors = ["Mark Melczer <melczer7@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.8"

[dev-dependencies]
approx = "0.4"
rand_chacha = "0.3"
