[package]
name = "simulation"
version = "0.1.0"
authors = ["Mark Melczer <melczer7@gmail.com>"]
edition = "2018"

[dependencies]
common = { path = "../common" }
genetic-algorithm = { path = "../genetic-algorithm" }
neural-net = { path = "../neural-net" }
