[package]
name = "neural-net"
version = "0.1.0"
authors = ["Mark Melczer <melczer7@gmail.com>"]
edition = "2018"

[dependencies]
common = { path = "../common" }

[dev-dependencies]
approx = "0.4"
common = { path = "../common", features = ["dev"] }
